/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HelloWorldRouteImport } from './routes/helloWorld'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomRoomNumberRouteImport } from './routes/room.$roomNumber'
import { Route as JoinRoomNumberRouteImport } from './routes/join.$roomNumber'

const HelloWorldRoute = HelloWorldRouteImport.update({
  id: '/helloWorld',
  path: '/helloWorld',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomNumberRoute = RoomRoomNumberRouteImport.update({
  id: '/room/$roomNumber',
  path: '/room/$roomNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoomNumberRoute = JoinRoomNumberRouteImport.update({
  id: '/join/$roomNumber',
  path: '/join/$roomNumber',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/helloWorld': typeof HelloWorldRoute
  '/join/$roomNumber': typeof JoinRoomNumberRoute
  '/room/$roomNumber': typeof RoomRoomNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/helloWorld': typeof HelloWorldRoute
  '/join/$roomNumber': typeof JoinRoomNumberRoute
  '/room/$roomNumber': typeof RoomRoomNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/helloWorld': typeof HelloWorldRoute
  '/join/$roomNumber': typeof JoinRoomNumberRoute
  '/room/$roomNumber': typeof RoomRoomNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/helloWorld' | '/join/$roomNumber' | '/room/$roomNumber'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/helloWorld' | '/join/$roomNumber' | '/room/$roomNumber'
  id:
    | '__root__'
    | '/'
    | '/helloWorld'
    | '/join/$roomNumber'
    | '/room/$roomNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelloWorldRoute: typeof HelloWorldRoute
  JoinRoomNumberRoute: typeof JoinRoomNumberRoute
  RoomRoomNumberRoute: typeof RoomRoomNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/helloWorld': {
      id: '/helloWorld'
      path: '/helloWorld'
      fullPath: '/helloWorld'
      preLoaderRoute: typeof HelloWorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomNumber': {
      id: '/room/$roomNumber'
      path: '/room/$roomNumber'
      fullPath: '/room/$roomNumber'
      preLoaderRoute: typeof RoomRoomNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$roomNumber': {
      id: '/join/$roomNumber'
      path: '/join/$roomNumber'
      fullPath: '/join/$roomNumber'
      preLoaderRoute: typeof JoinRoomNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelloWorldRoute: HelloWorldRoute,
  JoinRoomNumberRoute: JoinRoomNumberRoute,
  RoomRoomNumberRoute: RoomRoomNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
